name: Build and deploy to IBM Cloud Foundry

on:
  push:
    branches:
      - master

env:
  IBM_CLOUD_REGION: au-syd
  IBM_CLOUD_GROUP: Default
  IBM_CLOUD_SPACE: dev2
  IBM_CLOUD_ORG: caedanlavender@gmail.com
  MANIFEST_NAME: manifest.yml
  IBM_CLOUD_API: ${{secrets.IBM_CLOUD_API_KEY}}

defaults:
  run:
    working-directory: ./

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install IBM CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
        shell: bash

      - name: Install CF plugin
        run: ibmcloud cf install -f
        shell: bash

      - name: Login to IBM Cloud
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_GROUP"
        shell: bash

      - name: Target CF
        run: ibmcloud target --cf-api https://api.$IBM_CLOUD_REGION.cf.cloud.ibm.com -r $IBM_CLOUD_REGION -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE
        shell: bash

      - name: Deploy manifest file
        run: ibmcloud cf push -f ./$MANIFEST_NAME
        shell: bash
